language: php

php:
  - '8.2'

services:
  - docker

env:
  global:
    - DB_CONNECTION=mysql
    - DB_DATABASE=boopro_assignment
    - DB_USERNAME=sail
    - DB_PASSWORD=password

before_install:
  - echo "extension = pdo_mysql" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - cp .env.example .env
  - composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
  - php artisan key:generate
  - php artisan migrate --force

script:
  - vendor/bin/phpunit

branches:
  only:
    - development

cache:
  directories:
    - $HOME/.composer/cache
